/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',
    content: [
        './src/**/*.{js,ts,jsx,tsx,mdx}',
        './app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        container: {
            center: true,
            padding: '1rem',
        },
        extend: {
            colors: {
                background: 'var(--background)',
                foreground: 'var(--foreground)',
                brand: {
                    DEFAULT: 'var(--primary)',
                    hover: 'var(--primary-hover)',
                    glow: 'var(--primary-glow)',
                    foreground: 'var(--primary-foreground)',
                    50: '#eef2ff',
                    100: '#e0e7ff',
                    200: '#c7d2fe',
                    300: '#a5b4fc',
                    400: '#818cf8',
                    500: '#6366f1',
                    600: '#2d5bff',
                    700: '#2045d6',
                    800: '#1a36b0',
                    900: '#14298a',
                },
                primary: {
                    DEFAULT: 'var(--primary)',
                    foreground: 'var(--primary-foreground)',
                    hover: 'var(--primary-hover)',
                    glow: 'var(--primary-glow)',
                },
                accent: {
                    DEFAULT: 'var(--accent)',
                    foreground: 'var(--accent-foreground)',
                    subtle: 'var(--accent-subtle)',
                },
                secondary: {
                    DEFAULT: 'var(--secondary)',
                    foreground: 'var(--secondary-foreground)',
                },
                muted: {
                    DEFAULT: 'var(--muted)',
                    foreground: 'var(--muted-foreground)',
                },
                card: {
                    DEFAULT: 'var(--card)',
                    foreground: 'var(--card-foreground)',
                    hover: 'var(--bg-card-hover)',
                },
                border: 'var(--border)',
                'border-hover': 'var(--border-hover)',
                input: 'var(--input)',
                ring: 'var(--ring)',
                surface: 'var(--bg-surface)',
                sidebar: 'var(--bg-sidebar)',
                'text-primary': 'var(--text-primary)',
                'text-secondary': 'var(--text-secondary)',
                'text-muted': 'var(--text-muted)',
                success: 'var(--success)',
                warning: 'var(--warning)',
                danger: 'var(--danger)',
            },
            borderRadius: {
                DEFAULT: 'var(--radius)',
                xl: 'calc(var(--radius) + 4px)',
                lg: 'calc(var(--radius) + 2px)',
                md: 'var(--radius)',
                sm: 'calc(var(--radius) - 2px)',
                xs: 'calc(var(--radius) - 4px)',
            },
            fontFamily: {
                display: ['var(--font-display)', 'var(--font-sans)', 'system-ui', 'sans-serif'],
                sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
                mono: ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
            },
            letterSpacing: {
                tightest: '-0.04em',
                tighter: '-0.025em',
                tight: '-0.015em',
                normal: '0',
                wide: '0.015em',
                wider: '0.025em',
            },
            fontSize: {
                'hero': ['2.5rem', { lineHeight: '3rem', letterSpacing: '-0.035em', fontWeight: '800' }],
                'display': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.025em', fontWeight: '700' }],
                'heading': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.015em', fontWeight: '600' }],
            },
            boxShadow: {
                'glow-brand': '0 0 24px var(--primary-glow), 0 0 48px rgba(45, 91, 255, 0.1)',
                'glow-subtle': '0 0 14px var(--primary-glow)',
                'card': '0 1px 3px rgba(0, 0, 0, 0.3), 0 1px 2px rgba(0, 0, 0, 0.2)',
                'card-elevated': '0 8px 32px rgba(0, 0, 0, 0.4), 0 2px 8px rgba(0, 0, 0, 0.25)',
            },
            animation: {
                'fade-in': 'fadeIn 200ms ease forwards',
                'fade-in-up': 'fadeInUp 200ms ease forwards',
                'stream-pulse': 'streamPulse 1.2s ease-in-out infinite',
                'shimmer': 'shimmer 1.5s infinite',
            },
            transitionTimingFunction: {
                'spring-bounce': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
            },
        },
    },
    plugins: [require('@tailwindcss/typography'), require('tailwindcss-animate')],
};